# Site settings
name: Tejas Patel
title: Tejas Patel | Software Engineer Intern
description: a back-end software engineer focused on building and solving real-world problems
url: https://tejasdal.github.io/
baseurl: ''
email: tejas.patel@dal.ca
cover: https://tejasdal.github.io/img/og.png
logo: https://tejasdal.github.io/img/emojis/technologist.png
resume: https://tejasdal.github.io/resume.pdf
social:
  - title: email
    url: mailto:tejas.patel@dal.ca
  - title: twitter
    url: https://twitter.com/tejasdal
  - title: instagram
    url: https://www.instagram.com/tejas__111/
  - title: hackerrank
    url: https://www.hackerrank.com/tejas010297?hr_r=1
  - title: github
    url: https://github.com/tejasdal
  - title: linkedin
    url: https://www.linkedin.com/in/tejasdal

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
